#!/bin/sh

#configuracion visual

#configuracion montires
xrandr --setprovideroutputsource 1 0
xrandr --auto

# cambiar nombre monitores, ver con xrandr
xrandr --output HDMI-0 --mode 1920x1080 --rate 180 --primary \
       --output eDP-1-0 --mode 1920x1080 --right-of HDMI-0 &

#bordes color y grosor
bspc config border_width 2
bspc config focused_border_color "#da9c14"
bspc config normal_border_color "#AEA282"
bspc config presel_feedback_color "#f38ba8"

#separacion entre ventanas y margenes
bspc config window_gap 10 #espacio entre ventanas
bspc config top_padding 30
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10

#bordes desaparecen con solo una ventana activa
bspc config single_monocle_border off
bspc config borderless_monocle true
bspc config gapless_monocle true

#animaciones
picom --config ~/.config/picom/picom.conf -b &

#--------------------------------------

# Detener instancias duplicadas
pgrep -x sxhkd > /dev/null || sxhkd &

# Esperar a que X esté completamente listo
sleep 0.3

# Configurar cursor del mouse (importante para que aparezca al inicio)
xsetroot -cursor_name left_ptr &

# Configuración del teclado
setxkbmap latam

# Fondo de pantalla (con delay para esperar X)
(sleep 1 && feh --bg-fill /home/josue/Pictures/Wallpapers-gnome/fondo1.jpg) &

#-----------Inicio----------
# Lanzar compositor (esperar un poquito para no bloquear)
#pgrep -x picom > /dev/null || (sleep 0.5 && picom --config ~/.config/picom/picom.conf -b) &

#escritorios
bspc monitor -d 1 2 3 4 5 6 7 8 9

#enfocar con el mouse un nodo
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Barra
polybar mybar &

# Daemons útiles
nm-applet &
dunst &
sxhkd &
